#+title: Emacs Vanilla Config

* Intro
Coming from Doom Emacs (config [[https://github.com/roy-corentin/my-Doom-emacs-config][here]]) I want to try an Emacs config from vanilla to improve performance and make customization easier.
Do not be surprise to see some similarities in keybinding with Doom.

To improve performance I want to try to use as maximum possible only built-in packages. And the lighest package possible (see *Stack* section for more information)

I'm not a big fan of lazy loading, I prefer a slower startup but a faster application in use so there is not a lof of '=defer t=' in this config

* Stack
This is not an exhaustive list of package but only here to show important choices of important packages.

- Lsp: =Eglot=
- Workspace: =Tab-Bar mode=
- Package Manager: =Use-Package=
- Keybindings:
  - Global: =General=
  - Motion: =Evil=
- Completion:
  - MiniBuffer: =Vetico= (helm is too fat and slow)
  - In Buffer: =Corfu= (company is slow and fat too)
  - Search Algo: =Orderless=
  - Backend: =Cape=
- Git: =Magit= (of course)
- Major Modes: =Tree-Sitter= one when possible (best perf)
